In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("insurance_fraud_data.csv")

In [3]:
df

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.592730,silver,26633.27819,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.352820,black,26707.46021,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.38583,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.97997,4064.569489,1000,1187.96,10.259629,2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.53474,6639.049156,1000,1622.67,12.449888,3,N
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.739270,gray,26718.21104,3382.4126,500,1055.60,9.730108,6,Y
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.91954,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.84418,5236.564274,500,1232.57,9.116981,4,N

In [4]:
#1
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12002 entries, 0 to 12001
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   claim_number        12002 non-null  int64
 1   age_of_driver       12002 non-null  int64
 2   gender              12002 non-null  object
 3   marital_status      12002 non-null  object
 4   safety_rating       12002 non-null  int64
 5   annual_income       12002 non-null  float64
 6   high_education      12002 non-null  int64
 7   address_change      12002 non-null  int64
 8   property_status     12002 non-null  object
 9   zip_code            12002 non-null  int64
 10  claim_date          12002 non-null  object
 11  claim_day_of_week   12002 non-null  object
 12  accident_site       12002 non-null  object
 13  past_num_of_claims  12002 non-null  int64
 14  witness_present     12002 non-null  object
 15  liab_prct           12002 non-null  int64
 16  channel             12002 non-null  object
 17  police_report       12002 non-null  int64
 18  age_of_vehicle      12002 non-null  object
 19  vehicle_category    12002 non-null  object
 20  vehicle_price       12002 non-null  float64
 21  vehicle_color       12002 non-null  object
 22  total_claim         12002 non-null  float64
 23  injury_claim        12002 non-null  object
 24  policy deductible   12002 non-null  int64
 25  annual premium      12002 non-null  float64
 26  days open           12002 non-null  float64
 27  form defects        12002 non-null  int64
 28  fraud reported      11994 non-null  object
dtypes: float64(5), int64(11), object(13)
memory usage: 2.7+ MB

In [5]:
#2
df.head(10)
df.head()

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.59273,silver,26633.27819,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.35282,black,26707.46021,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.42523,gray,15279.38583,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.34224,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.37675,red,34493.97997,4064.569489,1000,1187.96,10.259629,2,N

In [6]:
#3
df.tail()

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.53474,6639.049156,1000,1622.67,12.449888,3,N
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.739270,gray,26718.21104,3382.4126,500,1055.60,9.730108,6,Y
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.91954,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.84418,5236.564274,500,1232.57,9.116981,4,N

In [7]:
#4
df.shape #(12002, 29)

(12002, 29)

In [8]:
#5
df.shape[0]
df.shape[1]

29

In [9]:
#6
df.columns

Index(['claim_number', 'age_of_driver', 'gender', 'marital_status',
       'safety_rating', 'annual_income', 'high_education', 'address_change',
       'property_status', 'zip_code', 'claim_date', 'claim_day_of_week',
       'accident_site', 'past_num_of_claims', 'witness_present', 'liab_prct',
       'channel', 'police_report', 'age_of_vehicle', 'vehicle_category',
       'vehicle_price', 'vehicle_color', 'total_claim', 'injury_claim',
       'policy deductible', 'annual premium', 'days open', 'form defects',
       'fraud reported'],
      dtype='object')

In [10]:
#7
df.index

RangeIndex(start=0, stop=12002, step=1)

In [11]:
#8
df['age_of_driver'].nunique()

81

In [12]:
#9
df.isnull().sum()

claim_number          0
age_of_driver         0
gender                0
marital_status        0
safety_rating         0
annual_income         0
high_education        0
address_change        0
property_status       0
zip_code              0
claim_date            0
claim_day_of_week     0
accident_site         0
past_num_of_claims    0
witness_present       0
liab_prct             0
channel               0
police_report         0
age_of_vehicle        0
vehicle_category      0
vehicle_price         0
vehicle_color         0
total_claim           0
injury_claim          0
policy deductible     0
annual premium        0
days open             0
form defects          0
fraud reported        8
dtype: int64

In [13]:
#10
df[df['fraud reported'].isnull()]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
1289,209786112,32,F,0,82,55448.0,1,0,Rent,85077,...,Medium,19898.814190,blue,20098.93622,3358.692057,500,951.56,9.080746,3,NaN
3211,519250176,48,F,1,84,61915.2,1,0,Rent,85062,...,Large,47049.844170,black,16346.19982,1489.005872,1000,1622.67,9.377763,5,NaN
4736,312408576,51,F,1,87,62924.8,1,1,Own,15009,...,Medium,49593.549660,white,23276.58815,3397.727223,1000,999.43,3.559439,2,NaN
5486,569763072,24,F,1,58,50859.2,1,1,Own,85074,...,Compact,22119.128060,black,14075.65068,4553.076044,2000,1246.68,3.395804,5,NaN
8267,260257536,53,M,1,74,63508.8,1,0,Own,85082,...,Medium,4183.679984,black,26045.91336,2207.298072,500,1354.20,9.622821,3,NaN
9319,364372992,54,M,0,88,63840.0,1,0,Own,20105,...,Compact,9932.795821,silver,24569.73676,2571.976801,500,1055.60,9.508939,4,NaN
9864,416233728,37,F,1,83,57814.4,1,1,Own,80016,...,Medium,6741.585076,blue,34031.90421,4541.296474,500,1354.20,9.775764,2,NaN
10388,467907840,56,M,1,77,64401.6,1,1,Rent,85077,...,Compact,51092.226140,black,17701.18504,4033.114969,500,1082.36,10.469410,3,NaN

In [14]:
#11
df['age_of_driver'].sum()

np.int64(522389)

In [15]:
#12
df.gender.dtype

dtype('O')

In [16]:
#13
df.describe()

,claim_number,age_of_driver,safety_rating,annual_income,high_education,address_change,zip_code,past_num_of_claims,liab_prct,police_report,vehicle_price,total_claim,policy deductible,annual premium,days open,form defects
count,1.200200e+04,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000
mean,3.119801e+08,43.525162,73.702966,63658.226534,0.698134,0.576737,49762.387269,0.494918,49.770122,0.601066,22925.335594,22861.534958,1011.039827,1268.140663,8.799198,3.969588
std,1.795997e+08,12.201298,15.378967,17289.704559,0.459087,0.494097,29133.180765,0.956002,33.581191,0.489699,12108.888412,12197.334761,562.099581,231.670671,2.413533,1.986915
min,1.866240e+05,19.000000,2.000000,-1.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2261.507903,2583.428985,500.000000,433.330000,2.303305,0.000000
25%,1.561887e+08,35.000000,66.000000,56899.200000,0.000000,0.000000,20111.000000,0.000000,18.000000,0.000000,14087.559950,13832.784382,500.000000,1082.360000,8.025550,3.000000
50%,3.121908e+08,43.000000,76.000000,60899.200000,1.000000,1.000000,50027.000000,0.000000,50.000000,1.000000,20642.029325,20508.293695,1000.000000,1239.060000,9.268787,4.000000
75%,4.677938e+08,51.000000,85.000000,64697.600000,1.000000,1.000000,80036.750000,1.000000,82.000000,1.000000,29293.641235,29205.553660,1000.000000,1383.490000,10.307928,5.000000
max,6.220385e+08,278.000000,100.000000,257313.600000,1.000000,1.000000,85083.000000,6.000000,100.000000,1.000000,106991.684500,101818.964200,2000.000000,2047.590000,15.177169,13.000000

In [17]:
#14
df["gender"].value_counts()

gender
M    6216
F    5786
Name: count, dtype: int64

In [18]:
#15
df["annual_income"].mean()

np.float64(63658.226533577734)

In [19]:
#16
df.sort_values(by="age_of_driver")

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
5257,492459264,19,M,1,60,65952.32,1,1,Rent,15009,...,Compact,41470.452400,red,4860.476734,5727.95075,500,1354.20,3.913943,7,N
4278,156100608,19,F,1,94,47094.40,1,1,Rent,15037,...,Compact,21200.517930,gray,41692.513340,3930.05684,1000,1310.80,4.389017,6,N
2625,425647872,19,M,1,86,47110.40,1,1,Rent,85021,...,Large,22601.122400,black,12978.570150,4803.061271,2000,1155.97,9.261373,6,N
4003,59470848,19,M,0,74,47094.40,1,1,Rent,20158,...,Large,17480.720460,white,17825.888130,6961.735568,2000,1356.92,4.278993,4,N
1306,212958720,19,F,0,87,47091.20,1,0,Own,20106,...,Medium,34349.774600,other,43098.696520,4090.066248,2000,1188.51,7.940888,7,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7702,202652928,101,M,1,42,73854.40,0,0,Own,85023,...,Large,17169.837670,silver,12952.060830,4168.072078,500,1093.83,11.867458,4,Y
5426,546600960,123,F,1,74,77017.60,1,0,Own,20132,...,Large,30392.900240,silver,19209.762010,1070.666244,500,1055.60,4.676576,8,N
5644,1078272,180,F,1,87,83068.80,1,1,Own,20101,...,Medium,9223.388197,black,26935.007250,2678.252957,2000,1475.73,7.994253,7,N
7542,186665472,249,M,1,94,88302.40,0,0,Own,80040,...,Compact,10785.663760,gray,35005.872680,6366.632672,500,722.66,9.162071,5,N
7329,165867264,278,F,1,76,90040.00,1,0,Rent,80015,...,Large,7995.461039,black,19242.953210,10728.27333,1000,1361.45,9.831486,4,N

In [20]:
#17
df.groupby("accident_site").sum()

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
accident_site,,,,,,,,,,,,,,,,,,,,,
Highway,774833402884,108655,MFMFFFFFMFFMMFMMMFMFFMFMFFFMFFFMMFFMMMFMMFMMFM...,1010101011110001011110111111111111110001110010...,184831,1.572544e+08,1800,1452,OwnOwnRentRentOwnOwnRentOwnRentRentRentOwnOwnO...,124883184,...,LargeCompactCompactLargeMediumMediumLargeLarge...,5.681114e+07,silverredwhiteblackblackbluewhiteotherblackoth...,5.790348e+07,5196.5525523388.5680255335.4590145904.03243354...,2550500,3165917.91,21905.973922,9819,NYYYNNNNNNNNNNNYYNYNNNNNNNNNNYNYNNYNNNNNNYYNNY...
Local,1854603848448,258323,MMMFFMMFMFFMMFFFMMFFFMFMMMMFFFFFFFFFFMMFFMMMFF...,1110011000001010111011001011110111110111110111...,435241,3.789313e+08,4058,3417,OwnOwnOwnOwnOwnOwnRentRentOwnOwnOwnOwnRentOwnO...,292185206,...,MediumMediumMediumMediumLargeCompactLargeLarge...,1.356503e+08,blackgrayredwhiteblueblackgraysilverwhitegrayg...,1.351141e+08,7957.2676413014.1108844064.5694892812.36526542...,5969500,7530451.33,52280.250642,23646,YNNYNNNNNNNYYNYNNNNYNNNYNYYNNYNNNNNYNYNYNNNNNY...
Parking Lot,1114947908352,155411,FMFFFMFMFMMMMFMFFFMFFFMFFFMMMMFFFFMMMMFFMFFFFF...,1111111011011011111110001100100100010000110110...,264511,2.278404e+08,2521,2053,OwnRentOwnOwnRentOwnOwnRentRentOwnOwnRentRentR...,180179782,...,MediumLargeLargeMediumCompactCompactMediumLarg...,8.268846e+07,redsilverblacksilversilverothersilverblacksilv...,8.136656e+07,5671.5990255712.2824949218.582453973.694785345...,3614500,4523855.00,31421.753735,14178,NNNYYYNYNYNYNYNYNNNNNNNNNNNYNNNYNNNNNYYYNNNNNN...

In [21]:
#18
df.sample(5)

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
1219,200081664,35,M,1,67,56896.0,1,0,Own,85013,...,Compact,14026.786420,gray,21010.33435,3199.435706,1000,988.93,8.688161,7,N
11566,580939776,34,F,1,43,56408.0,1,0,Own,50005,...,Large,6925.667702,other,59999.62574,4273.651823,500,1518.54,10.828396,2,N
11868,608539392,44,F,0,71,60524.8,1,0,Own,20149,...,Large,17383.362930,red,21395.19172,2504.451549,2000,1239.06,11.594785,1,N
7988,231061248,41,F,0,91,59392.0,1,0,Rent,80019,...,Compact,9766.814061,red,11370.66175,5759.61535,2000,1155.97,10.064969,4,N
11556,579032064,47,F,1,48,61585.6,0,1,Own,80041,...,Compact,22437.524820,blue,16985.06421,4445.634323,1000,1324.78,12.580308,8,N

In [22]:
#19
df.duplicated()
df.duplicated().sum()

np.int64(0)

In [23]:
#20
df[df['age_of_driver'] > 25]

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.592730,silver,26633.27819,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.352820,black,26707.46021,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.38583,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.97997,4064.569489,1000,1187.96,10.259629,2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.53474,6639.049156,1000,1622.67,12.449888,3,N
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.739270,gray,26718.21104,3382.4126,500,1055.60,9.730108,6,Y
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.91954,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.84418,5236.564274,500,1232.57,9.116981,4,N